<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>pandas3ed13</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../https://assets.qiufei.site/personal/profile.jpg" rel="icon" type="image/jpeg">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-681fbf911679f9b3dbf9743eb275ba49.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7e49aeac8059a213a463aa1a739e8272.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://qiufei.github.io"> 
<span class="menu-text">首页</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://qiufei.github.io/web-slide"> 
<span class="menu-text">课件</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<pre class="qmd"><code>---
title: "Python for Data Analysis: Data Analysis Examples"
author: "[Your Name]"
format:
  revealjs:
    theme: sky
    slide-number: true
    show-slide-number: all
    preview-links: true
    
---

## Introduction: Chapter 13 - Data Analysis Examples

::: {layout-ncol=2}
![](chapter13_introduction.png)

-   We've reached the final chapter! 🥳
-   Focus: Applying data analysis techniques to real-world datasets.
-   Goal: Extract meaningful insights from raw data.
-   The techniques demonstrated are widely applicable.
-   Datasets are available in the book's GitHub/Gitee repository.
:::

## Data Mining, Machine Learning, and Statistical Learning

::: {layout-ncol=2}
- Data mining, machine learning, and statistical learning share a common goal: to extract valuable insights and make predictions from data.

- The core of difference is the means to achieve the common goal.

```{mermaid}
graph LR
    A[Data Mining] --&gt; C(Common Ground)
    B[Machine Learning] --&gt; C
    D[Statistical Learning] --&gt; C
    C --&gt; E[Insights &amp; Predictions]</code></pre>
<p>:::</p>
<section id="data-mining" class="level2">
<h2 class="anchored" data-anchor-id="data-mining">Data Mining</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><p><strong>Definition:</strong> The process of discovering patterns, anomalies, and relationships in large datasets to predict outcomes.</p></li>
<li><p><strong>Focus:</strong> Discovering previously <em>unknown</em> patterns. It’s about exploration and finding something new.</p></li>
<li><p><strong>Techniques:</strong> Often uses a combination of methods from machine learning, statistics, and database systems.</p></li>
<li><p><strong>Example:</strong> A supermarket analyzing purchase data to discover that customers who buy diapers often also buy beer. This is an unexpected association.</p></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="datamining.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="machine-learning" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning">Machine Learning</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><p><strong>Definition</strong>: The study of computer algorithms that improve automatically through experience (data). Focuses on prediction and decision making.</p></li>
<li><p><strong>Focus</strong>: Building systems that can <em>learn from and make decisions</em> or predictions based on data, without explicit rules.</p></li>
<li><p><strong>Types</strong>:</p>
<ul>
<li><strong>Supervised Learning</strong>: Training a model on a labeled dataset (e.g., classifying emails as spam or not spam).</li>
<li><strong>Unsupervised Learning</strong>: Discovering hidden structures in unlabeled data (e.g., customer segmentation).</li>
<li><strong>Reinforcement Learning</strong>: Training agents to make a sequence of decisions by interacting with an environment (e.g., training a robot to walk).</li>
</ul></li>
<li><p><strong>Example</strong>: Training a model to predict house prices based on features like size, location, and number of bedrooms. The algorithm learns the relationship between features and price.</p></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="machinelearning.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="statistical-learning" class="level2">
<h2 class="anchored" data-anchor-id="statistical-learning">Statistical Learning</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><p><strong>Definition</strong>: A set of tools for modeling and understanding complex datasets. It’s a framework for applying statistical methods to learn from data.</p></li>
<li><p><strong>Focus</strong>: Emphasis on <em>models and their interpretability</em>, as well as precision and uncertainty. It bridges the gap between statistics and machine learning.</p></li>
<li><p><strong>Key Concepts</strong>:</p>
<ul>
<li><strong>Bias-Variance Tradeoff</strong>: Balancing the error introduced by approximating a real-world problem (bias) with the error introduced by the model’s sensitivity to the training data (variance).</li>
<li><strong>Model Selection</strong>: Choosing the best model from a set of candidate models.</li>
<li><strong>Regularization</strong>: Techniques to prevent overfitting by adding a penalty for complexity.</li>
</ul></li>
<li><p><strong>Example</strong>: Using linear regression to understand the relationship between advertising spending and sales, including confidence intervals for the coefficients.</p></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="statisticallearning.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="bitly-data-from-1.usa.gov" class="level2">
<h2 class="anchored" data-anchor-id="bitly-data-from-1.usa.gov">13.1 Bitly Data from 1.USA.gov</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Background:</strong>
<ul>
<li>In 2011, Bitly (URL shortening service) partnered with USA.gov.</li>
<li>Provided anonymized data from users shortening links ending in .gov or .mil.</li>
<li>Data was available as hourly snapshots (text files).</li>
<li>Service is now discontinued, but the data is preserved for analysis.</li>
</ul></li>
<li><strong>Data Format:</strong>
<ul>
<li>Each line in the file is a JSON (JavaScript Object Notation) object.</li>
<li>JSON is a human-readable text format for representing data.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="bitly_data_intro.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="json-data-example" class="level2">
<h2 class="anchored" data-anchor-id="json-data-example">JSON Data Example</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span> <span class="dt">"a"</span><span class="fu">:</span> <span class="st">"Mozilla</span><span class="ch">\/</span><span class="st">5.0 (Windows NT 6.1; WOW64) AppleWebKit</span><span class="ch">\/</span><span class="st">535.11 (KHTML, like Gecko) Chrome</span><span class="ch">\/</span><span class="st">17.0.963.78 Safari</span><span class="ch">\/</span><span class="st">535.11"</span><span class="fu">,</span> <span class="dt">"c"</span><span class="fu">:</span> <span class="st">"US"</span><span class="fu">,</span> <span class="dt">"nk"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span> <span class="dt">"tz"</span><span class="fu">:</span> <span class="st">"America</span><span class="ch">\/</span><span class="st">New_York"</span><span class="fu">,</span> <span class="dt">"gr"</span><span class="fu">:</span> <span class="st">"MA"</span><span class="fu">,</span> <span class="dt">"g"</span><span class="fu">:</span> <span class="st">"A6q0VH"</span><span class="fu">,</span> <span class="dt">"h"</span><span class="fu">:</span> <span class="st">"wfLQtf"</span><span class="fu">,</span> <span class="dt">"l"</span><span class="fu">:</span> <span class="st">"orofrog"</span><span class="fu">,</span> <span class="dt">"al"</span><span class="fu">:</span> <span class="st">"en-US,en;q=0.8"</span><span class="fu">,</span> <span class="dt">"hh"</span><span class="fu">:</span> <span class="st">"1.usa.gov"</span><span class="fu">,</span> <span class="dt">"r"</span><span class="fu">:</span> <span class="st">"http:</span><span class="ch">\/\/</span><span class="st">www.facebook.com</span><span class="ch">\/</span><span class="st">l</span><span class="ch">\/</span><span class="st">7AQEFzjSi</span><span class="ch">\/</span><span class="st">1.usa.gov</span><span class="ch">\/</span><span class="st">wfLQtf"</span><span class="fu">,</span> <span class="dt">"u"</span><span class="fu">:</span> <span class="st">"http:</span><span class="ch">\/\/</span><span class="st">www.ncbi.nlm.nih.gov</span><span class="ch">\/</span><span class="st">pubmed</span><span class="ch">\/</span><span class="st">22415991"</span><span class="fu">,</span> <span class="dt">"t"</span><span class="fu">:</span> <span class="dv">1331923247</span><span class="fu">,</span> <span class="dt">"hc"</span><span class="fu">:</span> <span class="dv">1331822918</span><span class="fu">,</span> <span class="dt">"cy"</span><span class="fu">:</span> <span class="st">"Danvers"</span><span class="fu">,</span> <span class="dt">"ll"</span><span class="fu">:</span> <span class="ot">[</span> <span class="fl">42.576698</span><span class="ot">,</span> <span class="fl">-70.954903</span> <span class="ot">]</span> <span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Structure:</strong> JSON objects are enclosed in curly braces <code>{}</code>.</li>
<li><strong>Key-Value Pairs:</strong> Data is stored as key-value pairs (e.g., <code>"a": "Mozilla/..."</code>).</li>
<li><strong>Data Types:</strong> Values can be strings, numbers, arrays (like <code>"ll"</code>), or other JSON objects.</li>
<li><strong>Python and JSON</strong>: Python has built-in libraries like <code>json</code> which easily converts JSON string into Python Dictionary.</li>
</ul>
</section>
<section id="reading-json-data-in-python" class="level2">
<h2 class="anchored" data-anchor-id="reading-json-data-in-python">Reading JSON Data in Python</h2>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> <span class="st">"datasets/bitly_usagov/example.txt"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(path) <span class="im">as</span> f:</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    records <span class="op">=</span> [json.loads(line) <span class="cf">for</span> line <span class="kw">in</span> f]  <span class="co"># List comprehension</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(records[<span class="dv">0</span>]) <span class="co"># Print the first record</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>import json</code></strong>: Imports the necessary JSON library.</li>
<li><strong><code>open(path)</code></strong>: Opens the file.</li>
<li><strong><code>json.loads(line)</code></strong>: Parses a single line of JSON text into a Python dictionary.</li>
<li><strong>List Comprehension</strong>: <code>[... for line in f]</code> efficiently creates a list of dictionaries, one for each line in the file.</li>
<li><strong><code>records</code></strong>: Now holds a list of Python dictionaries, each representing a record from the dataset.</li>
</ul>
</section>
<section id="accessing-data-in-the-dictionary" class="level2">
<h2 class="anchored" data-anchor-id="accessing-data-in-the-dictionary">Accessing Data in the Dictionary</h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(records[<span class="dv">0</span>][<span class="st">'tz'</span>])  <span class="co"># Accessing the 'tz' (time zone) field of the first record</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>After loading the JSON data, you can access individual fields within each record using standard dictionary key access (square brackets).</li>
<li><code>records[0]</code> gets the first dictionary in the list.</li>
<li><code>['tz']</code> accesses the value associated with the key “tz”.</li>
</ul>
</section>
<section id="counting-time-zones-pure-python" class="level2">
<h2 class="anchored" data-anchor-id="counting-time-zones-pure-python">Counting Time Zones (Pure Python)</h2>
<ul>
<li><strong>Objective:</strong> Determine the most frequent time zones in the dataset (the <code>tz</code> field).</li>
<li><strong>Approach 1: Using a Dictionary and Loop</strong></li>
<li><strong>Approach 2： Using <code>defaultdict</code></strong></li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> defaultdict</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_counts2(sequence):</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> defaultdict(<span class="bu">int</span>)  <span class="co"># Values will initialize to 0</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> x <span class="kw">in</span> sequence:</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        counts[x] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>defaultdict(int)</code></strong>: Creates a dictionary where, if a key is not found, it’s automatically added with a default value of 0 (provided by <code>int()</code>). This avoids the <code>if x in counts</code> check.</li>
</ul>
</section>
<section id="counting-time-zones-pure-python---continued" class="level2">
<h2 class="anchored" data-anchor-id="counting-time-zones-pure-python---continued">Counting Time Zones (Pure Python) - continued</h2>
<ul>
<li><strong>Key Error Explanation</strong>: If the data does <em>not</em> contain the <code>'tz'</code> key, a <code>KeyError</code> will be raised, as shown on the slide.</li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Initial Code (causes KeyError)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># time_zones = [rec["tz"] for rec in records]</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Corrected with if condition</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>time_zones <span class="op">=</span> [rec[<span class="st">"tz"</span>] <span class="cf">for</span> rec <span class="kw">in</span> records <span class="cf">if</span> <span class="st">"tz"</span> <span class="kw">in</span> rec]</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(time_zones[:<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>The corrected code adds an <code>if "tz" in rec</code> condition to the list comprehension. This ensures that we only try to access the <code>tz</code> key if it actually exists in the record. This prevents the <code>KeyError</code>.</li>
</ul>
</section>
<section id="counting-time-zones-pure-python---continued-1" class="level2">
<h2 class="anchored" data-anchor-id="counting-time-zones-pure-python---continued-1">Counting Time Zones (Pure Python) - continued</h2>
<ul>
<li><strong>Top 10 Time Zones:</strong></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> top_counts(count_dict, n<span class="op">=</span><span class="dv">10</span>):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    value_key_pairs <span class="op">=</span> [(count, tz) <span class="cf">for</span> tz, count <span class="kw">in</span> count_dict.items()]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    value_key_pairs.sort()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> value_key_pairs[<span class="op">-</span>n:]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#OR Using the Counter Class</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>counts <span class="op">=</span> Counter(time_zones)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(counts.most_common(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>top_counts</code> function:</strong> A custom function to get the top <em>n</em> most frequent items. It sorts the (count, item) pairs.</li>
<li><strong><code>Counter</code> class:</strong> A more efficient and Pythonic way to count items. <code>most_common(10)</code> directly returns the top 10.</li>
</ul>
</section>
<section id="counting-time-zones-pandas" class="level2">
<h2 class="anchored" data-anchor-id="counting-time-zones-pandas">Counting Time Zones (pandas)</h2>
<ul>
<li><strong>pandas DataFrame:</strong> A much more powerful and convenient way to work with tabular data.</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>frame <span class="op">=</span> pd.DataFrame(records)  <span class="co"># Create a DataFrame from the list of dictionaries</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame.info()) <span class="co"># Summary information about DataFrame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>pd.DataFrame(records)</code></strong>: Converts the list of dictionaries (<code>records</code>) into a pandas DataFrame. pandas automatically infers column names and data types.</li>
<li><strong><code>frame.info()</code></strong>: Provides a concise summary of the DataFrame, including:
<ul>
<li>Number of rows and columns.</li>
<li>Column names and data types.</li>
<li>Non-null value counts (shows missing data).</li>
<li>Memory usage.</li>
</ul></li>
</ul>
</section>
<section id="frame.info-output-explained" class="level2">
<h2 class="anchored" data-anchor-id="frame.info-output-explained"><code>frame.info()</code> Output Explained</h2>
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 3560 entries, 0 to 3559
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   a            3440 non-null   object
 1   c            2919 non-null   object
 ...
 16  _heartbeat_  120 non-null    float64
 17  kw           93 non-null     object
dtypes: float64(4), object(14)
memory usage: 500.8+ KB</code></pre>
<ul>
<li><strong><code>RangeIndex</code></strong>: Shows the total number of rows (3560) and their index range (0 to 3559).</li>
<li><strong><code>Data columns</code></strong>: Lists each column, its non-null count, and data type.
<ul>
<li><code>object</code>: Usually means text (strings).</li>
<li><code>float64</code>: Floating-point numbers.</li>
<li><code>int64</code>: Integer numbers.</li>
</ul></li>
<li><strong><code>Non-Null Count</code></strong>: Highlights missing values. For example, the <code>c</code> column has only 2919 non-null values, meaning 3560 - 2919 = 641 values are missing.</li>
<li><strong><code>dtypes</code></strong> and <strong><code>memory usage</code></strong>: Summary information.</li>
</ul>
</section>
<section id="working-with-time-zones-in-pandas" class="level2">
<h2 class="anchored" data-anchor-id="working-with-time-zones-in-pandas">Working with Time Zones in pandas</h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'tz'</span>].head())  <span class="co"># Display the first few time zones</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>tz_counts <span class="op">=</span> frame[<span class="st">'tz'</span>].value_counts()  <span class="co"># Count occurrences of each time zone</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tz_counts.head())</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Handling Missing Data</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>clean_tz <span class="op">=</span> frame[<span class="st">'tz'</span>].fillna(<span class="st">'Missing'</span>)  <span class="co"># Replace NaN values with "Missing"</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>clean_tz[clean_tz <span class="op">==</span> <span class="st">''</span>] <span class="op">=</span> <span class="st">'Unknown'</span>      <span class="co"># Replace empty strings with "Unknown"</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>tz_counts <span class="op">=</span> clean_tz.value_counts()</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tz_counts.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>frame['tz']</code></strong>: Selects the ‘tz’ column (a pandas Series).</li>
<li><strong><code>.head()</code></strong>: Shows the first 5 rows (by default).</li>
<li><strong><code>.value_counts()</code></strong>: Calculates the number of occurrences of each unique value in the Series. This is a <em>much</em> easier way to count time zones than the pure Python methods.</li>
<li><strong><code>.fillna('Missing')</code></strong>: Replaces missing values (represented as <code>NaN</code> in pandas) with the string “Missing”.</li>
<li><strong><code>clean_tz[clean_tz == ''] = 'Unknown'</code></strong>: Replaces empty strings (which represent unknown time zones) with “Unknown”. This is boolean indexing.</li>
</ul>
</section>
<section id="visualization-with-seaborn" class="level2">
<h2 class="anchored" data-anchor-id="visualization-with-seaborn">Visualization with seaborn</h2>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> tz_counts.head()</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>sns.barplot(y<span class="op">=</span>subset.index, x<span class="op">=</span>subset.to_numpy())</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>plt.show() <span class="co"># Display the plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>import seaborn as sns</code></strong>: Imports the seaborn library, which is built on top of matplotlib and provides a higher-level interface for creating attractive statistical graphics.</li>
<li><strong><code>subset = tz_counts.head()</code></strong>: use the top few time zones for clearer visualization.</li>
<li><strong><code>sns.barplot(y=subset.index, x=subset.to_numpy())</code></strong>: Creates a horizontal bar plot.
<ul>
<li><code>y=subset.index</code>: Sets the time zone names (the index of the <code>tz_counts</code> Series) as the y-axis labels.</li>
<li><code>x=subset.to_numpy()</code>: Sets the counts as the x-axis values. Convert <code>subset</code> Series to numpy array.</li>
</ul></li>
<li><strong><code>plt.show()</code></strong>: Displays the plot. Without this, the plot might not be shown.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="time_zone_barplot.png" class="img-fluid figure-img"></p>
<figcaption>‘Top time zones in the 1.usa.gov sample data’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="analyzing-browseragent-information" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-browseragent-information">Analyzing Browser/Agent Information</h2>
<div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'a'</span>][<span class="dv">1</span>])</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'a'</span>][<span class="dv">50</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(frame[<span class="st">'a'</span>][<span class="dv">51</span>][:<span class="dv">50</span>])  <span class="co"># Show first 50 characters</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> pd.Series([x.split()[<span class="dv">0</span>] <span class="cf">for</span> x <span class="kw">in</span> frame[<span class="st">'a'</span>].dropna()])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results.head())</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results.value_counts().head(<span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>The <code>a</code> field contains information about the user’s browser, device, or application.</li>
<li><strong><code>frame['a'][1]</code> ,etc.</strong>: Access and print specific agent strings.</li>
<li><strong><code>.dropna()</code></strong>: Removes rows where the ‘a’ value is missing (NaN) <em>before</em> splitting.</li>
<li><strong><code>x.split()[0]</code></strong>: Splits the agent string by spaces and takes the <em>first</em> element. This usually gives you the main browser identifier (e.g., “Mozilla/5.0”, “GoogleMaps/RochesterNY”).</li>
<li><strong><code>pd.Series(...)</code></strong>: Creates a pandas Series from the list of split agent strings.</li>
<li><strong><code>results.value_counts().head(8)</code></strong>: Counts the occurrences of each unique browser identifier and shows the top 8.</li>
</ul>
</section>
<section id="windows-vs.-non-windows-users" class="level2">
<h2 class="anchored" data-anchor-id="windows-vs.-non-windows-users">Windows vs.&nbsp;Non-Windows Users</h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>cframe <span class="op">=</span> frame[frame[<span class="st">'a'</span>].notna()].copy()  <span class="co"># Create a copy to avoid warnings</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>cframe[<span class="st">'os'</span>] <span class="op">=</span> np.where(cframe[<span class="st">'a'</span>].<span class="bu">str</span>.contains(<span class="st">'Windows'</span>), <span class="st">'Windows'</span>, <span class="st">'Not Windows'</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cframe[<span class="st">'os'</span>].head())</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>by_tz_os <span class="op">=</span> cframe.groupby([<span class="st">'tz'</span>, <span class="st">'os'</span>])</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>agg_counts <span class="op">=</span> by_tz_os.size().unstack().fillna(<span class="dv">0</span>) <span class="co"># Group, count, reshape, and fill missing values</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(agg_counts.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> Analyze time zone data separately for Windows and non-Windows users.</li>
<li><strong><code>cframe = frame[frame['a'].notna()].copy()</code></strong>: Creates a <em>copy</em> of the DataFrame, filtering out rows where the ‘a’ field is missing. Using <code>.copy()</code> avoids a <code>SettingWithCopyWarning</code> that pandas might raise.</li>
<li><strong><code>cframe['a'].str.contains('Windows')</code></strong>: Checks if the agent string contains “Windows” (case-sensitive). Returns a boolean Series.</li>
<li><strong><code>np.where(...)</code></strong>: A vectorized way to create a new ‘os’ column based on the condition. If the agent string contains “Windows”, the ‘os’ value is “Windows”; otherwise, it’s “Not Windows”.</li>
<li><strong><code>cframe.groupby(['tz', 'os'])</code></strong>: Groups the data by time zone <em>and</em> operating system.</li>
<li><strong><code>.size()</code></strong>: Counts the number of records in each group (similar to <code>value_counts()</code>, but for grouped data).</li>
<li><strong><code>.unstack()</code></strong>: Reshapes the data. It pivots the ‘os’ level from the index to become columns, making it easier to compare Windows and Not Windows counts for each time zone.</li>
<li><strong><code>.fillna(0)</code></strong>: Replaces any missing values (which would occur if a time zone had only Windows or only Not Windows users) with 0.</li>
</ul>
</section>
<section id="finding-the-most-popular-time-zones" class="level2">
<h2 class="anchored" data-anchor-id="finding-the-most-popular-time-zones">Finding the Most Popular Time Zones</h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1: Using argsort</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>indexer <span class="op">=</span> agg_counts.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>).argsort()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(indexer.values[:<span class="dv">10</span>])</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>count_subset <span class="op">=</span> agg_counts.take(indexer[<span class="op">-</span><span class="dv">10</span>:])</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(count_subset)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 2: Using nlargest (more convenient)</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(agg_counts.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>).nlargest(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><p><strong>Goal</strong>: Identify the time zones with the highest overall counts (combining Windows and Not Windows).</p></li>
<li><p><strong><code>agg_counts.sum(axis="columns")</code></strong>: Calculates the total count for each time zone (summing across the ‘Windows’ and ‘Not Windows’ columns).</p></li>
<li><p><strong><code>argsort()</code></strong>: Returns the <em>indices</em> that would sort the array. <code>indexer</code> now holds the indices of time zones, from least frequent to most frequent.</p></li>
<li><p><strong><code>.take(indexer[-10:])</code></strong>: Selects the rows corresponding to the top 10 time zones (the last 10 indices in <code>indexer</code>).</p></li>
<li><p><strong><code>nlargest(10)</code></strong>: A more direct way to get the top 10 time zones. It returns a Series with the time zones and their counts.</p></li>
</ul>
</section>
<section id="visualizing-windows-and-non-windows-users" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-windows-and-non-windows-users">Visualizing Windows and Non-Windows Users</h2>
<div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data for plotting</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>count_subset <span class="op">=</span> count_subset.stack()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>count_subset.name <span class="op">=</span> <span class="st">'total'</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>count_subset <span class="op">=</span> count_subset.reset_index()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(count_subset.head())</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span><span class="st">'total'</span>, y<span class="op">=</span><span class="st">'tz'</span>, hue<span class="op">=</span><span class="st">'os'</span>, data<span class="op">=</span>count_subset)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>count_subset.stack()</code></strong>: Pivots the ‘os’ column back into the index, creating a multi-level index (tz, os). This is the opposite of <code>unstack()</code>. It’s a common preparation step for seaborn plotting.</li>
<li><strong><code>count_subset.name = 'total'</code></strong>: Assigns the name “total” to the Series values (the counts).</li>
<li><strong><code>count_subset.reset_index()</code></strong>: Converts the multi-level index (‘tz’, ‘os’) into regular columns. This makes the data suitable for seaborn’s <code>barplot</code>.</li>
<li><strong><code>sns.barplot(x='total', y='tz', hue='os', data=count_subset)</code></strong>: Creates a grouped bar plot.
<ul>
<li><code>x='total'</code>: The ‘total’ column (counts) is used for the x-axis.</li>
<li><code>y='tz'</code>: The ‘tz’ column (time zone names) is used for the y-axis.</li>
<li><code>hue='os'</code>: The ‘os’ column is used to color the bars (creating separate bars for Windows and Not Windows).</li>
<li><code>data=count_subset</code>: Specifies the DataFrame to use.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="windows_vs_notwindows.png" class="img-fluid figure-img"></p>
<figcaption>‘Top time zones by Windows and non-Windows users’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="normalizing-counts" class="level2">
<h2 class="anchored" data-anchor-id="normalizing-counts">Normalizing Counts</h2>
<div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> norm_total(group):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    group[<span class="st">'normed_total'</span>] <span class="op">=</span> group[<span class="st">'total'</span>] <span class="op">/</span> group[<span class="st">'total'</span>].<span class="bu">sum</span>()</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> group</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> count_subset.groupby(<span class="st">'tz'</span>).<span class="bu">apply</span>(norm_total)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span><span class="st">'normed_total'</span>, y<span class="op">=</span><span class="st">'tz'</span>, hue<span class="op">=</span><span class="st">'os'</span>, data<span class="op">=</span>results)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Goal:</strong> Compare the <em>proportion</em> of Windows and non-Windows users within each time zone, rather than the raw counts.</li>
<li><strong><code>norm_total(group)</code> function:</strong>
<ul>
<li>Takes a group (DataFrame) as input.</li>
<li>Calculates <code>normed_total</code>: the count for each OS within the time zone, divided by the <em>total</em> count for that time zone. This gives the proportion.</li>
<li>Returns the modified group.</li>
</ul></li>
<li><strong><code>count_subset.groupby('tz').apply(norm_total)</code></strong>: Applies the <code>norm_total</code> function to each time zone group.</li>
<li><strong><code>sns.barplot(...)</code></strong>: Creates a bar plot, similar to before, but now using ‘normed_total’ to show proportions. This makes it easier to compare the relative prevalence of Windows and non-Windows users in different time zones.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="normalized_plot.png" class="img-fluid figure-img"></p>
<figcaption>‘Percentage Windows and non-Windows users in top occurring time zones’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="movielens-1m-dataset" class="level2">
<h2 class="anchored" data-anchor-id="movielens-1m-dataset">13.2 MovieLens 1M Dataset</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Dataset:</strong> MovieLens 1M, collected by GroupLens Research.</li>
<li><strong>Contents:</strong>
<ul>
<li>1 million movie ratings.</li>
<li>~6,000 users.</li>
<li>~4,000 movies.</li>
</ul></li>
<li><strong>Data Format:</strong> Three tables:
<ul>
<li><code>users</code>: User demographics (age, gender, occupation, zip code).</li>
<li><code>ratings</code>: User ID, movie ID, rating, timestamp.</li>
<li><code>movies</code>: Movie title, genres.</li>
</ul></li>
<li><strong>Goal:</strong> Explore relationships between ratings, demographics, and movie genres.</li>
<li><strong>Loading Data:</strong></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>unames <span class="op">=</span> [<span class="st">'user_id'</span>, <span class="st">'gender'</span>, <span class="st">'age'</span>, <span class="st">'occupation'</span>, <span class="st">'zip'</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>users <span class="op">=</span> pd.read_table(<span class="st">'datasets/movielens/users.dat'</span>, sep<span class="op">=</span><span class="st">'::'</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                      header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>unames, engine<span class="op">=</span><span class="st">'python'</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>rnames <span class="op">=</span> [<span class="st">'user_id'</span>, <span class="st">'movie_id'</span>, <span class="st">'rating'</span>, <span class="st">'timestamp'</span>]</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ratings <span class="op">=</span> pd.read_table(<span class="st">'datasets/movielens/ratings.dat'</span>, sep<span class="op">=</span><span class="st">'::'</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                        header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>rnames, engine<span class="op">=</span><span class="st">'python'</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>mnames <span class="op">=</span> [<span class="st">'movie_id'</span>, <span class="st">'title'</span>, <span class="st">'genres'</span>]</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>movies <span class="op">=</span> pd.read_table(<span class="st">'datasets/movielens/movies.dat'</span>, sep<span class="op">=</span><span class="st">'::'</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                       header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>mnames, engine<span class="op">=</span><span class="st">'python'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Key Arguments of <code>pd.read_table</code>:</strong>
<ul>
<li><code>sep='::'</code>: The separator between fields is two colons, and the default separator is a comma.</li>
<li><code>header=None</code>: The data files don’t have header rows, so we specify <code>None</code>.</li>
<li><code>names=unames</code> (etc.): We provide the column names.</li>
<li><code>engine='python'</code>: Use the python parsing engine, because the default C parsing engine does not support multi-character separators.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="movielens_data_intro.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="merging-the-data" class="level2">
<h2 class="anchored" data-anchor-id="merging-the-data">Merging the Data</h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.merge(pd.merge(ratings, users), movies)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.head())</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(data.iloc[<span class="dv">0</span>])  <span class="co"># Access the first row using iloc</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>pd.merge()</code></strong>: Combines DataFrames based on common columns. pandas automatically finds the common columns (e.g., ‘user_id’, ‘movie_id’).</li>
<li><strong>Two Merges:</strong>
<ol type="1">
<li><code>pd.merge(ratings, users)</code>: Merges <code>ratings</code> and <code>users</code> based on <code>user_id</code>.</li>
<li><code>pd.merge(..., movies)</code>: Merges the result with <code>movies</code> based on <code>movie_id</code>.</li>
</ol></li>
<li><strong><code>data</code></strong>: Now contains all the information in a single DataFrame.</li>
<li><strong><code>data.iloc[0]</code></strong>: show the first record in the combined <code>data</code>.</li>
</ul>
</section>
<section id="analyzing-ratings-by-gender" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-ratings-by-gender">Analyzing Ratings by Gender</h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mean_ratings <span class="op">=</span> data.pivot_table(<span class="st">'rating'</span>, index<span class="op">=</span><span class="st">'title'</span>, columns<span class="op">=</span><span class="st">'gender'</span>, aggfunc<span class="op">=</span><span class="st">'mean'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mean_ratings.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>data.pivot_table(...)</code></strong>: A powerful way to reshape and aggregate data.
<ul>
<li><code>'rating'</code>: The values to aggregate (we want the average rating).</li>
<li><code>index='title'</code>: The movie title will be the row index.</li>
<li><code>columns='gender'</code>: Gender (‘M’ and ‘F’) will be the columns.</li>
<li><code>aggfunc='mean'</code> (default): Calculates the mean rating for each title/gender combination.</li>
</ul></li>
</ul>
</section>
<section id="filtering-by-number-of-ratings" class="level2">
<h2 class="anchored" data-anchor-id="filtering-by-number-of-ratings">Filtering by Number of Ratings</h2>
<div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ratings_by_title <span class="op">=</span> data.groupby(<span class="st">'title'</span>).size()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ratings_by_title.head())</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>active_titles <span class="op">=</span> ratings_by_title.index[ratings_by_title <span class="op">&gt;=</span> <span class="dv">250</span>]</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(active_titles)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>mean_ratings <span class="op">=</span> mean_ratings.loc[active_titles]</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mean_ratings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal</strong>: Focus on movies with a sufficient number of ratings.</li>
<li><strong><code>data.groupby('title').size()</code></strong>: Counts the number of ratings for each movie title. <code>.size()</code> is used for grouped data (similar to <code>value_counts()</code> for Series).</li>
<li><strong><code>active_titles = ...</code></strong>: Creates a list of movie titles that have at least 250 ratings (an arbitrary threshold).</li>
<li><strong><code>mean_ratings.loc[active_titles]</code></strong>: Filters the <code>mean_ratings</code> DataFrame to include only the movies in <code>active_titles</code>. This focuses the analysis on movies with more substantial rating data.</li>
</ul>
</section>
<section id="sorting-and-finding-top-films" class="level2">
<h2 class="anchored" data-anchor-id="sorting-and-finding-top-films">Sorting and Finding Top Films</h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>top_female_ratings <span class="op">=</span> mean_ratings.sort_values(<span class="st">"F"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top_female_ratings.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>mean_ratings.sort_values("F", ascending=False)</code></strong>: Sorts the <code>mean_ratings</code> DataFrame by the ‘F’ (female) column in descending order. This puts the movies with the highest average female ratings at the top.</li>
</ul>
</section>
<section id="measuring-rating-disagreement" class="level2">
<h2 class="anchored" data-anchor-id="measuring-rating-disagreement">Measuring Rating Disagreement</h2>
<div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mean_ratings[<span class="st">'diff'</span>] <span class="op">=</span> mean_ratings[<span class="st">'M'</span>] <span class="op">-</span> mean_ratings[<span class="st">'F'</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sorted_by_diff <span class="op">=</span> mean_ratings.sort_values(<span class="st">'diff'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_by_diff.head())  <span class="co"># Movies preferred by women</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sorted_by_diff[::<span class="op">-</span><span class="dv">1</span>].head())  <span class="co"># Movies preferred by men</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard deviation of rating, grouped by title</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>rating_std_by_title <span class="op">=</span> data.groupby(<span class="st">'title'</span>)[<span class="st">'rating'</span>].std()</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter down to active_titles</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>rating_std_by_title <span class="op">=</span> rating_std_by_title.loc[active_titles]</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Order Series by value in descending order</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rating_std_by_title.sort_values(ascending<span class="op">=</span><span class="va">False</span>)[:<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>mean_ratings['diff'] = ...</code></strong>: Creates a new column ‘diff’ that stores the difference between the average male rating and the average female rating.</li>
<li><strong><code>sorted_by_diff = ...</code></strong>: Sorts the DataFrame by the ‘diff’ column.
<ul>
<li><code>sorted_by_diff.head()</code>: Shows movies where women rated significantly higher than men.</li>
<li><code>sorted_by_diff[::-1].head()</code>: Reverses the order (<code>[::-1]</code>) and shows movies where men rated significantly higher than women.</li>
</ul></li>
<li>The standard deviation is another disagreement.</li>
</ul>
</section>
<section id="handling-movie-genres" class="level2">
<h2 class="anchored" data-anchor-id="handling-movie-genres">Handling Movie Genres</h2>
<div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Original genres format: "Animation|Children's|Comedy"</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>movies[<span class="st">'genre'</span>] <span class="op">=</span> movies.pop(<span class="st">'genres'</span>).<span class="bu">str</span>.split(<span class="st">'|'</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(movies.head())</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>movies_exploded <span class="op">=</span> movies.explode(<span class="st">'genre'</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(movies_exploded[:<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Problem</strong>: Movie genres are stored as pipe-separated strings (e.g., “Action|Adventure|Thriller”). This is difficult to analyze directly.</li>
<li><strong><code>movies['genres'].str.split('|')</code></strong>: Splits the ‘genres’ string by the ‘|’ character, creating a <em>list</em> of genres for each movie.</li>
<li><strong><code>.pop('genres')</code></strong>: Removes the original ‘genres’ column and returns it. This is done to replace the original column with the new list-based one.</li>
<li><strong><code>movies.explode('genre')</code></strong>: Transforms the DataFrame so that each movie-genre combination gets its own row. This is crucial for analyzing ratings by genre. For example, if a movie is both “Action” and “Comedy”, it will now have two rows in <code>movies_exploded</code>.</li>
</ul>
</section>
<section id="combining-all-data-and-grouping-by-genre" class="level2">
<h2 class="anchored" data-anchor-id="combining-all-data-and-grouping-by-genre">Combining All Data and Grouping by Genre</h2>
<div class="sourceCode" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ratings_with_genre <span class="op">=</span> pd.merge(pd.merge(movies_exploded, ratings), users)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ratings_with_genre.iloc[<span class="dv">0</span>])</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>genre_ratings <span class="op">=</span> (ratings_with_genre.groupby([<span class="st">'genre'</span>, <span class="st">'age'</span>])</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>                 [<span class="st">'rating'</span>].mean()</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>                 .unstack(<span class="st">'age'</span>))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(genre_ratings[:<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>ratings_with_genre = ...</code></strong>: Merges all three tables (<code>movies_exploded</code>, <code>ratings</code>, and <code>users</code>) to create a single DataFrame where each row represents a single rating, along with user demographics and the individual genre.</li>
<li><strong><code>ratings_with_genre.iloc[0]</code></strong>: Displays the first row of this combined DataFrame.</li>
<li><strong><code>genre_ratings = ...</code></strong>: Calculates the average rating for each genre/age group combination.
<ul>
<li><code>groupby(['genre', 'age'])</code>: Groups by genre and age.</li>
<li><code>['rating'].mean()</code>: Calculates the mean rating for each group.</li>
<li><code>.unstack('age')</code>: Pivots the ‘age’ level from the index to become columns, making it easy to compare ratings across age groups for each genre.</li>
</ul></li>
</ul>
</section>
<section id="us-baby-names-18802010" class="level2">
<h2 class="anchored" data-anchor-id="us-baby-names-18802010">13.3 US Baby Names 1880–2010</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><p><strong>Dataset:</strong> US Social Security Administration (SSA) baby name data.</p></li>
<li><p><strong>Time Period:</strong> 1880-2010.</p></li>
<li><p><strong>Data Format:</strong> One file per year, each containing:</p>
<ul>
<li>Name</li>
<li>Sex</li>
<li>Number of births</li>
</ul></li>
<li><p><strong>Example File (yob1880.txt):</strong></p>
<pre><code>Mary,F,7065
Anna,F,2604
...</code></pre></li>
<li><p><strong>Potential Analyses:</strong></p>
<ul>
<li>Name popularity trends over time.</li>
<li>Relative rank of names.</li>
<li>Changes in naming diversity.</li>
<li>Analysis of first/last letters, vowel/consonant usage.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="usbabynames_intro.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="loading-and-combining-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-and-combining-the-data">Loading and Combining the Data</h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load a single year (for demonstration)</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>names1880 <span class="op">=</span> pd.read_csv(<span class="st">'datasets/babynames/yob1880.txt'</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>                        names<span class="op">=</span>[<span class="st">'name'</span>, <span class="st">'sex'</span>, <span class="st">'births'</span>])</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(names1880)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(names1880.groupby(<span class="st">'sex'</span>)[<span class="st">'births'</span>].<span class="bu">sum</span>())</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load all years and combine into a single DataFrame</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>years <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1880</span>, <span class="dv">2011</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>pieces <span class="op">=</span> []</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> year <span class="kw">in</span> years:</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    path <span class="op">=</span> <span class="ss">f'datasets/babynames/yob</span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">.txt'</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    frame <span class="op">=</span> pd.read_csv(path, names<span class="op">=</span>[<span class="st">'name'</span>, <span class="st">'sex'</span>, <span class="st">'births'</span>])</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    frame[<span class="st">'year'</span>] <span class="op">=</span> year  <span class="co"># Add a 'year' column</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    pieces.append(frame)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> pd.concat(pieces, ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>names1880 = pd.read_csv(...)</code></strong>: Loads a single year’s data into a DataFrame. <code>names</code> argument assigns column titles.</li>
<li><strong><code>names1880.groupby('sex')['births'].sum()</code></strong>: Calculates the total births for each sex in 1880.</li>
<li><strong>Looping through years</strong>:
<ul>
<li><code>range(1880, 2011)</code>: Iterates through the years.</li>
<li><code>f'datasets/babynames/yob{year}.txt'</code>: Uses an f-string to construct the file path for each year.</li>
<li><code>frame['year'] = year</code>: Adds a ‘year’ column to each year’s DataFrame.</li>
<li><code>pieces.append(frame)</code>: Adds each year’s DataFrame to the <code>pieces</code> list.</li>
</ul></li>
<li><strong><code>names = pd.concat(pieces, ignore_index=True)</code></strong>: Combines all the DataFrames in the <code>pieces</code> list into a single DataFrame (<code>names</code>).
<ul>
<li><code>ignore_index=True</code>: Resets the index, so we don’t have duplicate index values from the individual year files.</li>
</ul></li>
</ul>
</section>
<section id="aggregating-by-year-and-sex" class="level2">
<h2 class="anchored" data-anchor-id="aggregating-by-year-and-sex">Aggregating by Year and Sex</h2>
<div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>total_births <span class="op">=</span> names.pivot_table(<span class="st">'births'</span>, index<span class="op">=</span><span class="st">'year'</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                                 columns<span class="op">=</span><span class="st">'sex'</span>, aggfunc<span class="op">=</span><span class="bu">sum</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_births.tail())</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>total_births.plot(title<span class="op">=</span><span class="st">'Total births by sex and year'</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>names.pivot_table(...)</code></strong>: Calculates the total births for each year/sex combination.
<ul>
<li><code>'births'</code>: The values to aggregate (total births).</li>
<li><code>index='year'</code>: The year will be the row index.</li>
<li><code>columns='sex'</code>: Sex (‘F’ and ‘M’) will be the columns.</li>
<li><code>aggfunc=sum</code>: Calculates the sum of births for each year/sex combination.</li>
</ul></li>
<li><strong><code>total_births.tail()</code></strong>: Displays the last few rows of the result.</li>
<li><strong><code>total_births.plot(...)</code></strong>: Creates a line plot showing the trend of total births over time, separated by sex.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="birth_by_sex_year.png" class="img-fluid figure-img"></p>
<figcaption>‘Total births by sex and year’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="calculating-proportion-of-each-name" class="level2">
<h2 class="anchored" data-anchor-id="calculating-proportion-of-each-name">Calculating Proportion of Each Name</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_prop(group):</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    group[<span class="st">'prop'</span>] <span class="op">=</span> group[<span class="st">'births'</span>] <span class="op">/</span> group[<span class="st">'births'</span>].<span class="bu">sum</span>()</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> group</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> names.groupby([<span class="st">'year'</span>, <span class="st">'sex'</span>]).<span class="bu">apply</span>(add_prop)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(names)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> Determine the proportion of babies given each name <em>within each year and sex</em>. This normalizes the data, accounting for changes in the total number of births.</li>
<li><strong><code>add_prop(group)</code> function:</strong>
<ul>
<li>Takes a group (DataFrame) as input. A group represents a specific year and sex.</li>
<li><code>group['births'] / group['births'].sum()</code>: Calculates the proportion. It divides the births for each name by the <em>total</em> births for that year and sex.</li>
<li>Returns the modified group with the new ‘prop’ column.</li>
</ul></li>
<li><strong><code>names.groupby(['year', 'sex']).apply(add_prop)</code></strong>: Applies the <code>add_prop</code> function to each year/sex group. This adds the ‘prop’ column to the entire <code>names</code> DataFrame.</li>
</ul>
</section>
<section id="verifying-the-proportions" class="level2">
<h2 class="anchored" data-anchor-id="verifying-the-proportions">Verifying the Proportions</h2>
<div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(names.groupby([<span class="st">'year'</span>, <span class="st">'sex'</span>])[<span class="st">'prop'</span>].<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Sanity Check</strong>: It’s a good practice to verify that the calculations are correct.</li>
<li><strong><code>names.groupby(['year', 'sex'])['prop'].sum()</code></strong>: Groups by year and sex, and then sums the ‘prop’ column for each group. The result should be 1.0 for each year/sex combination, because the proportions should add up to 100%.</li>
</ul>
</section>
<section id="extracting-the-top-1000-names" class="level2">
<h2 class="anchored" data-anchor-id="extracting-the-top-1000-names">Extracting the Top 1000 Names</h2>
<div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_top1000(group):</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> group.sort_values(<span class="st">'births'</span>, ascending<span class="op">=</span><span class="va">False</span>)[:<span class="dv">1000</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>grouped <span class="op">=</span> names.groupby([<span class="st">'year'</span>, <span class="st">'sex'</span>])</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>top1000 <span class="op">=</span> grouped.<span class="bu">apply</span>(get_top1000)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>top1000 <span class="op">=</span> top1000.reset_index(drop<span class="op">=</span><span class="va">True</span>)  <span class="co"># Drop the hierarchical index</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(top1000)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> For each year and sex, find the 1000 most popular names. This subset is used for further analysis.</li>
<li><strong><code>get_top1000(group)</code> function:</strong>
<ul>
<li>Takes a group (DataFrame) as input (a specific year and sex).</li>
<li><code>group.sort_values('births', ascending=False)</code>: Sorts the names within the group by the number of births in descending order (most popular first).</li>
<li><code>[:1000]</code>: Selects the top 1000 rows (the top 1000 names).</li>
<li>Returns the top 1000 names.</li>
</ul></li>
<li><strong><code>names.groupby(['year', 'sex']).apply(get_top1000)</code></strong>: Applies the <code>get_top1000</code> function to each year/sex group, creating <code>top1000</code> DataFrame.</li>
<li><strong><code>top1000.reset_index(drop=True)</code>:</strong> remove the multi-level index</li>
</ul>
</section>
<section id="analyzing-naming-trends" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-naming-trends">Analyzing Naming Trends</h2>
<div class="sourceCode" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>boys <span class="op">=</span> top1000[top1000[<span class="st">'sex'</span>] <span class="op">==</span> <span class="st">'M'</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>girls <span class="op">=</span> top1000[top1000[<span class="st">'sex'</span>] <span class="op">==</span> <span class="st">'F'</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>total_births <span class="op">=</span> top1000.pivot_table(<span class="st">'births'</span>, index<span class="op">=</span><span class="st">'year'</span>, columns<span class="op">=</span><span class="st">'name'</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                                    aggfunc<span class="op">=</span><span class="bu">sum</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total_births.info())</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> total_births[[<span class="st">'John'</span>, <span class="st">'Harry'</span>, <span class="st">'Mary'</span>, <span class="st">'Marilyn'</span>]]</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>subset.plot(subplots<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">10</span>), title<span class="op">=</span><span class="st">"Number of births per year"</span>)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>boys = top1000[top1000['sex'] == 'M']</code></strong> and <strong><code>girls = ...</code></strong>: Creates separate DataFrames for boy and girl names.</li>
<li><strong><code>total_births = top1000.pivot_table(...)</code></strong>: Creates a pivot table to analyze the trend of specific names over time.
<ul>
<li><code>'births'</code>: The values to aggregate (total births).</li>
<li><code>index='year'</code>: The year will be the row index.</li>
<li><code>columns='name'</code>: Each unique name will become a column.</li>
<li><code>aggfunc=sum</code>: Sums the births for each name in each year.</li>
</ul></li>
<li><strong><code>subset.plot(...)</code></strong>: Plots the trends of selected names over time.
<ul>
<li><code>subplots=True</code>: Creates a separate subplot for each name.</li>
<li><code>figsize=(12, 10)</code>: Sets the figure size.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="boyandgirlnames.png" class="img-fluid figure-img"></p>
<figcaption>‘A few boy and girl names over time’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="measuring-the-increase-in-naming-diversity" class="level2">
<h2 class="anchored" data-anchor-id="measuring-the-increase-in-naming-diversity">Measuring the Increase in Naming Diversity</h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> top1000.pivot_table(<span class="st">'prop'</span>, index<span class="op">=</span><span class="st">'year'</span>, columns<span class="op">=</span><span class="st">'sex'</span>, aggfunc<span class="op">=</span><span class="bu">sum</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>table.plot(title<span class="op">=</span><span class="st">'Sum of table1000.prop by year and sex'</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>           yticks<span class="op">=</span>np.linspace(<span class="dv">0</span>, <span class="fl">1.2</span>, <span class="dv">13</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> boys[boys[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2010</span>]</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>prop_cumsum <span class="op">=</span> df[<span class="st">'prop'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).cumsum()</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prop_cumsum[:<span class="dv">10</span>])</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prop_cumsum.searchsorted(<span class="fl">0.5</span>)) <span class="co"># result 116, plus 1</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> boys[boys.year <span class="op">==</span> <span class="dv">1900</span>]</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>in1900 <span class="op">=</span> df.sort_values(<span class="st">'prop'</span>, ascending<span class="op">=</span><span class="va">False</span>).prop.cumsum()</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(in1900.searchsorted(<span class="fl">0.5</span>) <span class="op">+</span> <span class="dv">1</span>) <span class="co">#result 25</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Goal:</strong> Investigate whether naming has become more diverse over time (i.e., are parents choosing from a wider variety of names?).</li>
<li><strong><code>table = top1000.pivot_table(...)</code></strong>: Calculates the <em>sum</em> of the ‘prop’ column for each year and sex. This shows the total proportion of births represented by the top 1000 names. If this proportion <em>decreases</em> over time, it suggests increasing diversity.</li>
<li><strong><code>prop_cumsum = ... .cumsum()</code></strong>: Calculates the <em>cumulative sum</em> of the ‘prop’ column for boy names in 2010 (after sorting in descending order). This is a key step to find the number of names needed to reach 50% of total births.</li>
<li><strong><code>prop_cumsum.searchsorted(0.5)</code></strong>: Finds the index where the cumulative sum reaches 0.5 (50%). Because array index start from 0, plus 1.</li>
<li>Similar steps for 1900.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prop_top1000.png" class="img-fluid figure-img"></p>
<figcaption>‘Proportion of births represented in top one thousand names by sex’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="measuring-the-increase-in-naming-diversity-cont." class="level2">
<h2 class="anchored" data-anchor-id="measuring-the-increase-in-naming-diversity-cont.">Measuring the Increase in Naming Diversity (Cont.)</h2>
<div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_quantile_count(group, q<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    group <span class="op">=</span> group.sort_values(<span class="st">'prop'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> group.prop.cumsum().searchsorted(q) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>diversity <span class="op">=</span> top1000.groupby([<span class="st">'year'</span>, <span class="st">'sex'</span>]).<span class="bu">apply</span>(get_quantile_count)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>diversity <span class="op">=</span> diversity.unstack()</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>diversity.plot(title<span class="op">=</span><span class="st">"Number of popular names in top 50%"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>get_quantile_count(group, q=0.5)</code> function:</strong>
<ul>
<li>Takes a group (year/sex) and a quantile (defaulting to 0.5 for 50%) as input.</li>
<li>Sorts the group by ‘prop’ in descending order.</li>
<li>Calculates the cumulative sum of ‘prop’.</li>
<li>Uses <code>searchsorted(q)</code> to find the index where the cumulative sum reaches the specified quantile (0.5). Plus 1.</li>
<li>Returns the index.</li>
</ul></li>
<li><strong><code>top1000.groupby(['year', 'sex']).apply(get_quantile_count)</code></strong>: Applies this function to each year/sex group to calculate the number of names needed to reach 50% of births for each group.</li>
<li><strong><code>diversity.unstack()</code></strong>: Reshapes the result for easier plotting.</li>
<li>The plot shows how the number of names required to reach 50% of total births has changed over time, separated by sex.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="diversity.png" class="img-fluid figure-img"></p>
<figcaption>‘Plot of diversity metric by year’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="the-last-letter-revolution" class="level2">
<h2 class="anchored" data-anchor-id="the-last-letter-revolution">The “Last Letter” Revolution</h2>
<div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_last_letter(x):</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>last_letters <span class="op">=</span> names[<span class="st">'name'</span>].<span class="bu">map</span>(get_last_letter)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>last_letters.name <span class="op">=</span> <span class="st">'last_letter'</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> names.pivot_table(<span class="st">'births'</span>, index<span class="op">=</span>last_letters,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                          columns<span class="op">=</span>[<span class="st">'sex'</span>, <span class="st">'year'</span>], aggfunc<span class="op">=</span><span class="bu">sum</span>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>subtable <span class="op">=</span> table.reindex(columns<span class="op">=</span>[<span class="dv">1910</span>, <span class="dv">1960</span>, <span class="dv">2010</span>], level<span class="op">=</span><span class="st">'year'</span>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(subtable.head())</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(subtable.<span class="bu">sum</span>())</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>letter_prop <span class="op">=</span> subtable <span class="op">/</span> subtable.<span class="bu">sum</span>()</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(letter_prop.head())</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>letter_prop[<span class="st">'M'</span>].plot(kind<span class="op">=</span><span class="st">'bar'</span>, rot<span class="op">=</span><span class="dv">0</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], title<span class="op">=</span><span class="st">'Male'</span>)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>letter_prop[<span class="st">'F'</span>].plot(kind<span class="op">=</span><span class="st">'bar'</span>, rot<span class="op">=</span><span class="dv">0</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>], title<span class="op">=</span><span class="st">'Female'</span>,</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>                      legend<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Idea:</strong> Analyze the distribution of the last letters of baby names over time.</li>
<li><strong><code>get_last_letter(x)</code> function:</strong> Returns the last character of a string.</li>
<li><strong><code>names['name'].map(get_last_letter)</code></strong>: Applies this function to the ‘name’ column, creating a new Series <code>last_letters</code> containing the last letter of each name.</li>
<li><strong><code>table = names.pivot_table(...)</code></strong>: Creates a pivot table to count births by last letter, sex, and year.</li>
<li><strong><code>subtable = ...</code></strong>: Selects data for specific years (1910, 1960, 2010) for comparison.</li>
<li><strong><code>letter_prop = subtable / subtable.sum()</code></strong>: Calculates the <em>proportion</em> of names ending in each letter for each sex and year. This normalizes the data.</li>
<li><strong><code>plt.subplots(2, 1, ...)</code></strong>: Creates a figure with two subplots (one for male, one for female).</li>
<li><strong><code>letter_prop['M'].plot(...)</code></strong> and <strong><code>letter_prop['F'].plot(...)</code></strong>: Creates bar plots showing the distribution of last letters for each sex.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="letter_prop.png" class="img-fluid figure-img"></p>
<figcaption>‘Proportion of boy and girl names ending in each letter’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="the-last-letter-revolution-cont." class="level2">
<h2 class="anchored" data-anchor-id="the-last-letter-revolution-cont.">The “Last Letter” Revolution (Cont.)</h2>
<div class="sourceCode" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>letter_prop <span class="op">=</span> table <span class="op">/</span> table.<span class="bu">sum</span>()</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>dny_ts <span class="op">=</span> letter_prop.loc[[<span class="st">'d'</span>, <span class="st">'n'</span>, <span class="st">'y'</span>], <span class="st">'M'</span>].T</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dny_ts.head())</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>dny_ts.plot()</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>letter_prop = table / table.sum()</code></strong>: Calculates proportions based on the <em>full</em> table (all years).</li>
<li><strong><code>dny_ts = letter_prop.loc[['d', 'n', 'y'], 'M'].T</code></strong>: Selects data for specific letters (‘d’, ‘n’, ‘y’) and for males (‘M’), and then transposes the result (. T). This creates a time series where each column is a letter and each row is a year.</li>
<li><strong><code>dny_ts.plot()</code></strong>: Plots the trends of these letters over time.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="boy_dny.png" class="img-fluid figure-img"></p>
<figcaption>‘Proportion of boys born with names ending in d/n/y over time’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="boy-names-that-became-girl-names-and-vice-versa" class="level2">
<h2 class="anchored" data-anchor-id="boy-names-that-became-girl-names-and-vice-versa">Boy Names That Became Girl Names (and Vice Versa)</h2>
<div class="sourceCode" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>all_names <span class="op">=</span> pd.Series(top1000[<span class="st">'name'</span>].unique())</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>lesley_like <span class="op">=</span> all_names[all_names.<span class="bu">str</span>.contains(<span class="st">'Lesl'</span>)]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(lesley_like)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>filtered <span class="op">=</span> top1000[top1000[<span class="st">'name'</span>].isin(lesley_like)]</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(filtered.groupby(<span class="st">'name'</span>)[<span class="st">'births'</span>].<span class="bu">sum</span>())</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> filtered.pivot_table(<span class="st">'births'</span>, index<span class="op">=</span><span class="st">'year'</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                            columns<span class="op">=</span><span class="st">'sex'</span>, aggfunc<span class="op">=</span><span class="st">'sum'</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> table.div(table.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>), axis<span class="op">=</span><span class="st">"index"</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(table.tail())</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>table.plot(style<span class="op">=</span>{<span class="st">'M'</span>: <span class="st">'k-'</span>, <span class="st">'F'</span>: <span class="st">'k--'</span>})</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Goal:</strong> Identify names that have switched gender preference over time.</li>
<li><strong><code>all_names = ...</code></strong>: Gets a list of all <em>unique</em> names in the <code>top1000</code> DataFrame.</li>
<li><strong><code>lesley_like = ...</code></strong>: Filters this list to find names containing “Lesl” (e.g., Lesley, Leslie, Leslee).</li>
<li><strong><code>filtered = ...</code></strong>: Selects rows from <code>top1000</code> where the name is in the <code>lesley_like</code> list.</li>
<li><strong><code>filtered.groupby('name')['births'].sum()</code></strong>: Calculates the total births for each of the “Lesley-like” names.</li>
<li><strong><code>table = filtered.pivot_table(...)</code></strong>: Creates a pivot table showing the number of births for each sex in each year.</li>
<li><strong><code>table = table.div(..., axis="index")</code></strong>: Calculates the <em>proportion</em> of births for each sex in each year. This normalizes the data.</li>
<li><strong><code>table.plot(...)</code></strong>: Plots the trend of male vs.&nbsp;female proportions for “Lesley-like” names over time.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lesleylike_names.png" class="img-fluid figure-img"></p>
<figcaption>‘Proportion of male/female Lesley-like names over time’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="usda-food-database" class="level2">
<h2 class="anchored" data-anchor-id="usda-food-database">13.4 USDA Food Database</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Dataset:</strong> USDA (United States Department of Agriculture) food nutrient database.</li>
<li><strong>Data Format:</strong> JSON.</li>
<li><strong>Example Record:</strong> (See the JSON structure in the original slide content).</li>
<li><strong>Goal:</strong> Analyze nutrient information for different foods.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="sourceCode" id="cb37"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"id"</span><span class="fu">:</span> <span class="dv">21441</span><span class="fu">,</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"description"</span><span class="fu">:</span> <span class="st">"KENTUCKY FRIED CHICKEN, Fried Chicken, EXTRA CRISPY, Wing, meat and skin with breading"</span><span class="fu">,</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"tags"</span><span class="fu">:</span> <span class="ot">[</span><span class="st">"KFC"</span><span class="ot">]</span><span class="fu">,</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"manufacturer"</span><span class="fu">:</span> <span class="st">"Kentucky Fried Chicken"</span><span class="fu">,</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"group"</span><span class="fu">:</span> <span class="st">"Fast Foods"</span><span class="fu">,</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"portions"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"amount"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"unit"</span><span class="fu">:</span> <span class="st">"wing, with skin"</span><span class="fu">,</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"grams"</span><span class="fu">:</span> <span class="fl">68.0</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"nutrients"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"value"</span><span class="fu">:</span> <span class="fl">20.8</span><span class="fu">,</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"units"</span><span class="fu">:</span> <span class="st">"g"</span><span class="fu">,</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"description"</span><span class="fu">:</span> <span class="st">"Protein"</span><span class="fu">,</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"group"</span><span class="fu">:</span> <span class="st">"Composition"</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="usda_food_intro.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="loading-and-exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-and-exploring-the-data">Loading and Exploring the Data</h2>
<div class="sourceCode" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>db <span class="op">=</span> json.load(<span class="bu">open</span>(<span class="st">'datasets/usda_food/database.json'</span>))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(db))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(db[<span class="dv">0</span>].keys())</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(db[<span class="dv">0</span>][<span class="st">'nutrients'</span>][<span class="dv">0</span>])</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>nutrients <span class="op">=</span> pd.DataFrame(db[<span class="dv">0</span>][<span class="st">'nutrients'</span>])</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nutrients.head(<span class="dv">7</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>import json</code></strong>: Imports the <code>json</code> library for working with JSON data.</li>
<li><strong><code>db = json.load(...)</code></strong>: Loads the JSON data from the file into a Python object (<code>db</code>). <code>db</code> will be a list of dictionaries.</li>
<li><strong><code>len(db)</code></strong>: Shows the number of food records in the database.</li>
<li><strong><code>db[0].keys()</code></strong>: Shows the keys (fields) in the first food record.</li>
<li><strong><code>db[0]['nutrients'][0]</code></strong>: Shows the first nutrient record for the first food.</li>
<li><strong><code>nutrients = pd.DataFrame(...)</code></strong>: Creates a DataFrame from the list of nutrients for the <em>first</em> food. This is just a preliminary step.</li>
</ul>
</section>
<section id="extracting-food-information" class="level2">
<h2 class="anchored" data-anchor-id="extracting-food-information">Extracting Food Information</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>info_keys <span class="op">=</span> [<span class="st">'description'</span>, <span class="st">'group'</span>, <span class="st">'id'</span>, <span class="st">'manufacturer'</span>]</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>info <span class="op">=</span> pd.DataFrame(db, columns<span class="op">=</span>info_keys)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(info.head())</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(info.info())</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.value_counts(info[<span class="st">'group'</span>])[:<span class="dv">10</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> Create a DataFrame (<code>info</code>) containing basic information about each food.</li>
<li><strong><code>info_keys = [...]</code></strong>: Defines a list of the keys we want to extract.</li>
<li><strong><code>info = pd.DataFrame(db, columns=info_keys)</code></strong>: Creates the DataFrame, selecting only the specified columns.</li>
<li><strong><code>info.head()</code></strong>: Displays the first few rows.</li>
<li><strong><code>info.info()</code></strong>: Provides summary information (column names, data types, missing values).</li>
<li><strong><code>pd.value_counts(info['group'])[:10]</code></strong>: Counts the occurrences of each food group and shows the top 10.</li>
</ul>
</section>
<section id="processing-nutrient-data" class="level2">
<h2 class="anchored" data-anchor-id="processing-nutrient-data">Processing Nutrient Data</h2>
<div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>nutrients <span class="op">=</span> []</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> rec <span class="kw">in</span> db:</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    fnuts <span class="op">=</span> pd.DataFrame(rec[<span class="st">'nutrients'</span>])</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    fnuts[<span class="st">'id'</span>] <span class="op">=</span> rec[<span class="st">'id'</span>]</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    nutrients.append(fnuts)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>nutrients <span class="op">=</span> pd.concat(nutrients, ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nutrients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal</strong>: Create a single DataFrame (<code>nutrients</code>) containing all nutrient information for all foods.</li>
<li><strong>Looping through records:</strong>
<ul>
<li><code>for rec in db:</code>: Iterates through each food record in the <code>db</code> list.</li>
<li><code>fnuts = pd.DataFrame(rec['nutrients'])</code>: Creates a DataFrame from the list of nutrients for the <em>current</em> food.</li>
<li><code>fnuts['id'] = rec['id']</code>: Adds the food ID to the <code>fnuts</code> DataFrame. This is crucial for linking nutrients back to the correct food.</li>
<li><code>nutrients.append(fnuts)</code>: Appends the <code>fnuts</code> DataFrame to the <code>nutrients</code> list.</li>
</ul></li>
<li><strong><code>nutrients = pd.concat(nutrients, ignore_index=True)</code></strong>: Combines all the individual nutrient DataFrames into a single DataFrame. <code>ignore_index=True</code> is important to avoid duplicate index values.</li>
</ul>
</section>
<section id="handling-duplicates-and-renaming" class="level2">
<h2 class="anchored" data-anchor-id="handling-duplicates-and-renaming">Handling Duplicates and Renaming</h2>
<div class="sourceCode" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>nutrients.duplicated().<span class="bu">sum</span>()  <span class="co"># Check for duplicates</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>nutrients <span class="op">=</span> nutrients.drop_duplicates()  <span class="co"># Remove duplicates</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>col_mapping <span class="op">=</span> {<span class="st">'description'</span> : <span class="st">'food'</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">'group'</span>       : <span class="st">'fgroup'</span>}</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>info <span class="op">=</span> info.rename(columns<span class="op">=</span>col_mapping, copy<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(info.info())</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>col_mapping <span class="op">=</span> {<span class="st">'description'</span> : <span class="st">'nutrient'</span>,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">'group'</span> : <span class="st">'nutgroup'</span>}</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>nutrients <span class="op">=</span> nutrients.rename(columns<span class="op">=</span>col_mapping, copy<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(nutrients)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Duplicate Check</strong>: It is found that some rows of nutritional information are duplicated and need to be removed before proceeding.</li>
<li><strong><code>nutrients.duplicated().sum()</code></strong>: Counts the number of duplicate rows in the <code>nutrients</code> DataFrame.</li>
<li><strong><code>nutrients = nutrients.drop_duplicates()</code></strong>: Removes duplicate rows.</li>
<li><strong>Renaming columns:</strong>
<ul>
<li><code>col_mapping = ...</code>: Creates dictionaries to map old column names to new ones. This improves clarity.</li>
<li><code>info = info.rename(..., copy=False)</code>: Renames columns in the <code>info</code> DataFrame. <code>copy=False</code> modifies the DataFrame in place (more efficient).</li>
<li><code>nutrients = nutrients.rename(...)</code>: Renames columns in the <code>nutrients</code> DataFrame.</li>
</ul></li>
</ul>
</section>
<section id="merging-dataframes" class="level2">
<h2 class="anchored" data-anchor-id="merging-dataframes">Merging DataFrames</h2>
<div class="sourceCode" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>ndata <span class="op">=</span> pd.merge(nutrients, info, on<span class="op">=</span><span class="st">'id'</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ndata.info())</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ndata.iloc[<span class="dv">30000</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>ndata = pd.merge(nutrients, info, on='id')</code></strong>: Combines the <code>nutrients</code> and <code>info</code> DataFrames based on the common ‘id’ column. This creates a single DataFrame with all food and nutrient information.</li>
<li><strong><code>ndata.info()</code></strong>: Displays summary information about the merged DataFrame.</li>
<li><strong><code>ndata.iloc[30000]</code></strong>: Shows a specific row (nutrient record) to illustrate the structure of the merged data.</li>
</ul>
</section>
<section id="plotting-median-nutrient-values" class="level2">
<h2 class="anchored" data-anchor-id="plotting-median-nutrient-values">Plotting Median Nutrient Values</h2>
<div class="sourceCode" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> ndata.groupby([<span class="st">'nutrient'</span>, <span class="st">'fgroup'</span>])[<span class="st">'value'</span>].quantile(<span class="fl">0.5</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>result[<span class="st">'Zinc, Zn'</span>].sort_values().plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Goal</strong>: Visualize the median values of nutrients for different food groups.</li>
<li><strong><code>result = ndata.groupby(['nutrient', 'fgroup'])['value'].quantile(0.5)</code></strong>:
<ul>
<li><code>groupby(['nutrient', 'fgroup'])</code>: Groups the data by nutrient and food group.</li>
<li><code>['value'].quantile(0.5)</code>: Calculates the median (50th percentile) of the ‘value’ column (nutrient amount) for each group.</li>
</ul></li>
<li><strong><code>result['Zinc, Zn'].sort_values().plot(kind='barh')</code></strong>:
<ul>
<li><code>result['Zinc, Zn']</code>: Selects the data for Zinc.</li>
<li><code>.sort_values()</code>: Sorts the median Zinc values in ascending order.</li>
<li><code>.plot(kind='barh')</code>: Creates a horizontal bar plot.</li>
</ul></li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="zinc_values_foodgroup.png" class="img-fluid figure-img"></p>
<figcaption>‘Median zinc values by food group’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="finding-foods-with-maximum-nutrient-values" class="level2">
<h2 class="anchored" data-anchor-id="finding-foods-with-maximum-nutrient-values">Finding Foods with Maximum Nutrient Values</h2>
<div class="sourceCode" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>by_nutrient <span class="op">=</span> ndata.groupby([<span class="st">'nutgroup'</span>, <span class="st">'nutrient'</span>])</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_maximum(x):</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x.loc[x.value.idxmax()]</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>max_foods <span class="op">=</span> by_nutrient.<span class="bu">apply</span>(get_maximum)[[<span class="st">'value'</span>, <span class="st">'food'</span>]]</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>max_foods[<span class="st">'food'</span>] <span class="op">=</span> max_foods[<span class="st">'food'</span>].<span class="bu">str</span>[:<span class="dv">50</span>]</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(max_foods.loc[<span class="st">'Amino Acids'</span>][<span class="st">'food'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal</strong>: Identify the food that has the highest value for each nutrient.</li>
<li><strong><code>by_nutrient = ndata.groupby(['nutgroup', 'nutrient'])</code></strong>: Groups the data by nutrient group and nutrient name.</li>
<li><strong><code>get_maximum(x)</code> function:</strong>
<ul>
<li>Takes a group (DataFrame) as input.</li>
<li><code>x.value.idxmax()</code>: Finds the <em>index</em> of the row with the maximum value in the ‘value’ column (the nutrient amount).</li>
<li><code>x.loc[...]</code>: Selects the row with the maximum value.</li>
<li>Returns the selected row.</li>
</ul></li>
<li><strong><code>max_foods = by_nutrient.apply(get_maximum)[['value', 'food']]</code></strong>: Applies the <code>get_maximum</code> function to each group and selects the ‘value’ and ‘food’ columns.</li>
<li><strong><code>max_foods['food'] = max_foods['food'].str[:50]</code></strong>: Shortens the food names to the first 50 characters for better display.</li>
</ul>
</section>
<section id="federal-election-commission-database" class="level2">
<h2 class="anchored" data-anchor-id="federal-election-commission-database">13.5 2012 Federal Election Commission Database</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Dataset:</strong> 2012 US Federal Election Commission (FEC) campaign contribution data.</li>
<li><strong>Contents:</strong>
<ul>
<li>Contributor names.</li>
<li>Occupation and employer.</li>
<li>Address.</li>
<li>Contribution amount.</li>
</ul></li>
<li><strong>Data Format:</strong> CSV (Comma-Separated Values).</li>
<li><strong>File:</strong> <code>P00000001-ALL.csv</code> (in the book’s data repository).</li>
<li><strong>Goal:</strong> Analyze patterns in campaign contributions.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="sourceCode" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>fec <span class="op">=</span> pd.read_csv(<span class="st">'datasets/fec/P00000001-ALL.csv'</span>, low_memory<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec.info())</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec.iloc[<span class="dv">123456</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>fec = pd.read_csv(...)</code></strong>: Loads the CSV data into a DataFrame.</li>
<li><strong><code>low_memory=False</code></strong>: An important option. The file is large, and pandas might guess data types incorrectly if <code>low_memory=True</code> (the default). Setting it to <code>False</code> ensures more accurate type inference, but uses more memory.</li>
<li><strong><code>fec.info()</code></strong>: Provides a summary of the DataFrame (columns, data types, missing values).</li>
<li><strong><code>fec.iloc[123456]</code></strong>: Displays a sample record.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="fec_intro.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="adding-party-affiliation" class="level2">
<h2 class="anchored" data-anchor-id="adding-party-affiliation">Adding Party Affiliation</h2>
<div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>unique_cands <span class="op">=</span> fec[<span class="st">'cand_nm'</span>].unique()</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(unique_cands)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>parties <span class="op">=</span> {<span class="st">'Bachmann, Michelle'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Cain, Herman'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Gingrich, Newt'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Huntsman, Jon'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Johnson, Gary Earl'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>           <span class="st">'McCotter, Thaddeus G'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Obama, Barack'</span>: <span class="st">'Democrat'</span>,</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Paul, Ron'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Pawlenty, Timothy'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Perry, Rick'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Roemer, Charles E. 'Buddy' III"</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Romney, Mitt'</span>: <span class="st">'Republican'</span>,</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>           <span class="st">'Santorum, Rick'</span>: <span class="st">'Republican'</span>}</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec[<span class="st">'cand_nm'</span>][<span class="dv">123456</span>:<span class="dv">123461</span>])</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec[<span class="st">'cand_nm'</span>][<span class="dv">123456</span>:<span class="dv">123461</span>].<span class="bu">map</span>(parties))</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>fec[<span class="st">'party'</span>] <span class="op">=</span> fec[<span class="st">'cand_nm'</span>].<span class="bu">map</span>(parties)</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec[<span class="st">'party'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>unique_cands = fec['cand_nm'].unique()</code></strong>: Gets a list of all unique candidate names.</li>
<li><strong><code>parties = {...}</code></strong>: Creates a dictionary mapping candidate names to their political party affiliations.</li>
<li><strong><code>fec['cand_nm'][123456:123461].map(parties)</code></strong>: Uses the <code>map</code> method to apply the <code>parties</code> dictionary to a subset of the ‘cand_nm’ column. This shows how the mapping works.</li>
<li><strong><code>fec['party'] = fec['cand_nm'].map(parties)</code></strong>: Creates a new ‘party’ column in the <code>fec</code> DataFrame, assigning a party affiliation to each record based on the candidate’s name.</li>
<li><strong><code>fec['party'].value_counts()</code></strong>: Counts the number of records for each political party.</li>
</ul>
</section>
<section id="filtering-contributions" class="level2">
<h2 class="anchored" data-anchor-id="filtering-contributions">Filtering Contributions</h2>
<div class="sourceCode" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((fec[<span class="st">'contb_receipt_amt'</span>] <span class="op">&gt;</span> <span class="dv">0</span>).value_counts())</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>fec <span class="op">=</span> fec[fec[<span class="st">'contb_receipt_amt'</span>] <span class="op">&gt;</span> <span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Problem</strong>: The dataset includes both contributions (positive amounts) and refunds (negative amounts).</li>
<li><strong><code>(fec['contb_receipt_amt'] &gt; 0).value_counts()</code></strong>: Checks how many contributions are positive and how many are negative.</li>
<li><strong><code>fec = fec[fec['contb_receipt_amt'] &gt; 0]</code></strong>: Filters the <code>fec</code> DataFrame to keep only records where the contribution amount is positive. This focuses the analysis on actual contributions.</li>
</ul>
</section>
<section id="filtering-by-candidate" class="level2">
<h2 class="anchored" data-anchor-id="filtering-by-candidate">Filtering by Candidate</h2>
<div class="sourceCode" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fec_mrbo <span class="op">=</span> fec[fec[<span class="st">'cand_nm'</span>].isin([<span class="st">'Obama, Barack'</span>, <span class="st">'Romney, Mitt'</span>])]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> Focus on contributions to the two main candidates (Obama and Romney).</li>
<li><strong><code>fec_mrbo = fec[fec['cand_nm'].isin(['Obama, Barack', 'Romney, Mitt'])]</code></strong>: Filters the <code>fec</code> DataFrame to keep only records where the candidate name is either “Obama, Barack” or “Romney, Mitt”.</li>
</ul>
</section>
<section id="donation-statistics-by-occupation-and-employer" class="level2">
<h2 class="anchored" data-anchor-id="donation-statistics-by-occupation-and-employer">Donation Statistics by Occupation and Employer</h2>
<div class="sourceCode" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(fec[<span class="st">'contbr_occupation'</span>].value_counts()[:<span class="dv">10</span>])</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>occ_mapping <span class="op">=</span> {</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'INFORMATION REQUESTED PER BEST EFFORTS'</span> : <span class="st">'NOT PROVIDED'</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'INFORMATION REQUESTED'</span> : <span class="st">'NOT PROVIDED'</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'INFORMATION REQUESTED (BEST EFFORTS)'</span> : <span class="st">'NOT PROVIDED'</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'C.E.O.'</span>: <span class="st">'CEO'</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_occ(x):</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If no mapping provided, return x</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> occ_mapping.get(x, x)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>fec[<span class="st">'contbr_occupation'</span>] <span class="op">=</span> fec[<span class="st">'contbr_occupation'</span>].<span class="bu">map</span>(get_occ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>fec['contbr_occupation'].value_counts()[:10]</code></strong>: Counts the number of contributions for each occupation and shows the top 10.</li>
<li><strong>Problem:</strong> There are many variations of similar occupations (e.g., “INFORMATION REQUESTED” in multiple forms). We need to clean this up.</li>
<li><strong><code>occ_mapping = {...}</code></strong>: Creates a dictionary to map variations of occupations to a standardized form (e.g., mapping all “INFORMATION REQUESTED” variants to “NOT PROVIDED”).</li>
<li><strong><code>get_occ(x)</code> function:</strong>
<ul>
<li>Uses the <code>get</code> method of the <code>occ_mapping</code> dictionary. If the occupation <code>x</code> is found in the dictionary, it returns the mapped value. If not, it returns the original occupation <code>x</code> (this is the “pass-through” behavior).</li>
</ul></li>
<li><strong><code>fec['contbr_occupation'] = fec['contbr_occupation'].map(get_occ)</code></strong>: Applies the <code>get_occ</code> function to the ‘contbr_occupation’ column to standardize the occupations.</li>
</ul>
</section>
<section id="donation-statistics-by-occupation-and-employer-cont." class="level2">
<h2 class="anchored" data-anchor-id="donation-statistics-by-occupation-and-employer-cont.">Donation Statistics by Occupation and Employer (Cont.)</h2>
<div class="sourceCode" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>emp_mapping <span class="op">=</span> {</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'INFORMATION REQUESTED PER BEST EFFORTS'</span> : <span class="st">'NOT PROVIDED'</span>,</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'INFORMATION REQUESTED'</span> : <span class="st">'NOT PROVIDED'</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SELF'</span> : <span class="st">'SELF-EMPLOYED'</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SELF EMPLOYED'</span> : <span class="st">'SELF-EMPLOYED'</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_emp(x):</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If no mapping provided, return x</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> emp_mapping.get(x, x)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>fec[<span class="st">'contbr_employer'</span>] <span class="op">=</span> fec[<span class="st">'contbr_employer'</span>].<span class="bu">map</span>(get_emp)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>by_occupation <span class="op">=</span> fec.pivot_table(<span class="st">'contb_receipt_amt'</span>,</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>                                index<span class="op">=</span><span class="st">'contbr_occupation'</span>,</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>                                columns<span class="op">=</span><span class="st">'party'</span>, aggfunc<span class="op">=</span><span class="st">'sum'</span>)</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>over_2mm <span class="op">=</span> by_occupation[by_occupation.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>) <span class="op">&gt;</span> <span class="dv">2000000</span>]</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(over_2mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>The process for employer is almost identical to occupation.</li>
<li><strong><code>by_occupation = fec.pivot_table(...)</code></strong>: Creates a pivot table to analyze contributions by occupation and party.
<ul>
<li><code>'contb_receipt_amt'</code>: The values to aggregate (contribution amounts).</li>
<li><code>index='contbr_occupation'</code>: Occupation will be the row index.</li>
<li><code>columns='party'</code>: Party (‘Democrat’ and ‘Republican’) will be the columns.</li>
<li><code>aggfunc='sum'</code>: Calculates the total contribution amount for each occupation/party combination.</li>
</ul></li>
<li><strong><code>over_2mm = ...</code></strong>: Filters the <code>by_occupation</code> DataFrame to keep only occupations with total contributions (across both parties) greater than $2 million.</li>
<li><strong><code>print(over_2mm)</code></strong>: Displays the resulting DataFrame.</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>over_2mm.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong><code>over_2mm.plot(kind='barh')</code></strong>: Creates a horizontal bar plot of the <code>over_2mm</code> DataFrame, visualizing total contributions by occupation and party.</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="donations_by_occupation.png" class="img-fluid figure-img"></p>
<figcaption>‘Total donations by party for top occupations’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="top-donor-occupations-and-employers" class="level2">
<h2 class="anchored" data-anchor-id="top-donor-occupations-and-employers">Top Donor Occupations and Employers</h2>
<div class="sourceCode" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_top_amounts(group, key, n<span class="op">=</span><span class="dv">5</span>):</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>    totals <span class="op">=</span> group.groupby(key)[<span class="st">'contb_receipt_amt'</span>].<span class="bu">sum</span>()</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> totals.nlargest(n)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>grouped <span class="op">=</span> fec_mrbo.groupby(<span class="st">'cand_nm'</span>)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped.<span class="bu">apply</span>(get_top_amounts, <span class="st">'contbr_occupation'</span>, n<span class="op">=</span><span class="dv">7</span>))</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped.<span class="bu">apply</span>(get_top_amounts, <span class="st">'contbr_employer'</span>, n<span class="op">=</span><span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong><code>get_top_amounts(group, key, n=5)</code> function:</strong>
<ul>
<li><code>group</code>: A DataFrame group (e.g., contributions for a specific candidate).</li>
<li><code>key</code>: The column to group by (e.g., ‘contbr_occupation’ or ‘contbr_employer’).</li>
<li><code>n</code>: The number of top items to return.</li>
<li><code>totals = group.groupby(key)['contb_receipt_amt'].sum()</code>: Calculates the total contribution amount for each unique value of the <code>key</code> (e.g., for each occupation).</li>
<li><code>return totals.nlargest(n)</code>: Returns the top <code>n</code> values (largest contributions).</li>
</ul></li>
<li><strong><code>grouped = fec_mrbo.groupby('cand_nm')</code></strong>: Groups the <code>fec_mrbo</code> DataFrame by candidate name.</li>
<li><strong><code>grouped.apply(get_top_amounts, 'contbr_occupation', n=7)</code></strong>: Applies the <code>get_top_amounts</code> function to each candidate group, finding the top 7 occupations for each candidate.</li>
<li><strong><code>grouped.apply(get_top_amounts, 'contbr_employer', n=10)</code></strong>: Does the same, but for employers and returns the top 10.</li>
</ul>
</section>
<section id="bucketing-donation-amounts" class="level2">
<h2 class="anchored" data-anchor-id="bucketing-donation-amounts">Bucketing Donation Amounts</h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> np.array([<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">100</span>, <span class="dv">1000</span>, <span class="dv">10000</span>, <span class="dv">100_000</span>, <span class="dv">1_000_000</span>, <span class="dv">10_000_000</span>])</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> pd.cut(fec_mrbo[<span class="st">'contb_receipt_amt'</span>], bins)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(labels)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>grouped <span class="op">=</span> fec_mrbo.groupby([<span class="st">'cand_nm'</span>, labels])</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(grouped.size().unstack(level<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>bucket_sums <span class="op">=</span> grouped[<span class="st">'contb_receipt_amt'</span>].<span class="bu">sum</span>().unstack(level<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>normed_sums <span class="op">=</span> bucket_sums.div(bucket_sums.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>),</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>                              axis<span class="op">=</span><span class="st">"index"</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(normed_sums)</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>normed_sums[:<span class="op">-</span><span class="dv">2</span>].plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<ul>
<li><strong>Goal:</strong> Analyze contributions based on donation size brackets.</li>
<li><strong><code>bins = np.array([...])</code></strong>: Defines the boundaries of the donation amount buckets.</li>
<li><strong><code>labels = pd.cut(fec_mrbo['contb_receipt_amt'], bins)</code></strong>: Uses the <code>cut</code> function to assign each contribution to a bucket based on its amount. <code>labels</code> is a pandas Categorical object.</li>
<li><strong><code>grouped = fec_mrbo.groupby(['cand_nm', labels])</code></strong>: Groups the data by candidate name <em>and</em> donation bucket.</li>
<li><strong><code>grouped.size().unstack(level=0)</code></strong>: Counts the number of contributions in each bucket for each candidate and reshapes the data for easier analysis.</li>
<li><strong><code>bucket_sums = ...</code></strong>: Calculates the <em>total</em> contribution amount within each bucket for each candidate.</li>
<li><strong><code>normed_sums = ...</code></strong>: Normalizes the data to show the <em>percentage</em> of total donations from each bucket for each candidate.</li>
<li><strong><code>normed_sums[:-2].plot(kind='barh')</code></strong>: Creates a horizontal bar plot, excluding the two largest buckets (which are likely from organizations, not individuals).</li>
</ul>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="donation_size.png" class="img-fluid figure-img"></p>
<figcaption>‘Percentage of total donations received by candidates for each donation size’</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="donation-statistics-by-state" class="level2">
<h2 class="anchored" data-anchor-id="donation-statistics-by-state">Donation Statistics by State</h2>
<div class="sourceCode" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>grouped <span class="op">=</span> fec_mrbo.groupby([<span class="st">'cand_nm'</span>, <span class="st">'contbr_st'</span>])</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>totals <span class="op">=</span> grouped[<span class="st">'contb_receipt_amt'</span>].<span class="bu">sum</span>().unstack(level<span class="op">=</span><span class="dv">0</span>).fillna(<span class="dv">0</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>totals <span class="op">=</span> totals[totals.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>) <span class="op">&gt;</span> <span class="dv">100000</span>]</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(totals.head(<span class="dv">10</span>))</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>percent <span class="op">=</span> totals.div(totals.<span class="bu">sum</span>(axis<span class="op">=</span><span class="st">"columns"</span>), axis<span class="op">=</span><span class="st">"index"</span>)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(percent.head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Goal:</strong> Analyze contributions based on the state of the contributor.</li>
<li><strong><code>grouped = fec_mrbo.groupby(['cand_nm', 'contbr_st'])</code></strong>: Groups the data by candidate name and contributor state.</li>
<li><strong><code>totals = grouped['contb_receipt_amt'].sum().unstack(level=0).fillna(0)</code></strong>: Calculates the total contribution amount from each state for each candidate.</li>
</ul>
<p><code>unstack(level=0)</code> pivots the candidate names to columns, and <code>fillna(0)</code> handles cases where a state might have no contributions for a particular candidate. - <strong><code>totals = totals[totals.sum(axis="columns") &gt; 100000]</code></strong>: Filters the data to keep only states with total contributions (across both candidates) greater than $100,000. - <strong><code>percent = totals.div(totals.sum(axis="columns"), axis="index")</code></strong>: Calculates the <em>percentage</em> of contributions from each state for each candidate. This normalizes the data.</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li>This chapter demonstrated how to apply Python data analysis techniques to real-world datasets.</li>
<li>We explored data from Bitly/USA.gov, MovieLens, US baby names, USDA food nutrients, and FEC campaign contributions.</li>
<li>Key techniques covered:
<ul>
<li>Data loading (text files, JSON, CSV).</li>
<li>Data cleaning and transformation (handling missing data, string manipulation, data type conversions).</li>
<li>Data aggregation and grouping (using <code>groupby</code>, <code>pivot_table</code>, <code>apply</code>).</li>
<li>Data merging and reshaping (<code>merge</code>, <code>concat</code>, <code>unstack</code>, <code>stack</code>).</li>
<li>Data visualization (using matplotlib and seaborn).</li>
<li>Working with time series data.</li>
</ul></li>
<li>The chapter emphasized iterative data exploration: starting with raw data, cleaning and transforming it, and gradually building up analyses to answer specific questions.</li>
</ul>
</section>
<section id="thoughts-and-discussion" class="level2">
<h2 class="anchored" data-anchor-id="thoughts-and-discussion">Thoughts and Discussion</h2>
<ul>
<li>How could these analyses be extended or refined? What other questions could you ask of these datasets?</li>
<li>Consider the limitations of the data and the analyses. What assumptions were made? What biases might be present?</li>
<li>How could these techniques be applied to other datasets you’re interested in?</li>
<li>What are the ethical considerations when working with real-world data, especially data about people (like baby names, movie ratings, or political contributions)?</li>
<li>Discuss the trade-offs between using pure Python, the collections module (Counter, defaultdict), and pandas for different tasks. When is each approach most appropriate?</li>
<li>How does the choice of visualization (bar plots, line plots, etc.) affect the insights you can gain from the data?</li>
<li>Explore the official documents of <code>pandas.DataFrame.merge</code>, <code>pandas.DataFrame.groupby</code>, <code>pandas.DataFrame.plot</code> and <code>pandas.DataFrame.apply</code> to deepen your understanding.</li>
<li>Consider how these skills are useful for a business major, providing a competitive edge in a future career.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/qiufei\.github\.io\/web-slide-r");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>🔋<a href="https://posit.co"><img src="https://posit.co/wp-content/themes/Posit/assets/images/posit-logo-2024.svg" class="img-fluid" alt="Posit" width="65"></a></p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 邱飞 © 2025
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://beian.miit.gov.cn">
<p>浙ICP备 2024072710号-1</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33021202002511">
<p>浙公网安备 33021202002511号</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:hfutqiufei@163.com">
      <i class="bi bi-envelope-at-fill" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>